name:                Haskell-Algorithms
version:             0.1.0.0
github:              "OliverFlecke/Haskell-Algorithms"
license:             BSD3
author:              "Oliver Fleckenstein"
maintainer:          "oliverflec@gmail.com"
copyright:           "2018 Oliver Fleckenstein"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/OliverFlecke/Haskell-Algorithms#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Haskell-Algorithms-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Algorithms

tests:
  Haskell-Algorithms-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-Algorithms
